export const seedProducts = [
  {
    name: 'Fat Burner Advanced 90 capsulas',
    slug: 'fat-burner-advanced-90-capsulas',
    description:
      'Quemador formulado para acompanar etapas de definicion con enfoque en metabolismo activo, energia diaria y control de peso.',
    price: 22990,
    comparePrice: 25990,
    stock: 20,
    category: 'control-peso',
    brand: 'Iron Fuel',
    goal: 'definicion',
    flavor: 'Sin sabor',
    featured: true,
    active: true,
    image: '/products/fat-burner-advanced-90-capsulas.png',
    images: ['/products/fat-burner-advanced-90-capsulas.png'],
  },
  {
    name: 'BCAA 2:1:1 sabor limon 400 g',
    slug: 'bcaa-sabor-limon-400g',
    description:
      'Blend de aminoacidos esenciales con leucina, isoleucina y valina para recuperacion muscular, hidratacion y menor fatiga durante el entrenamiento.',
    price: 26990,
    comparePrice: 29990,
    stock: 16,
    category: 'aminoacidos',
    brand: 'Iron Fuel',
    goal: 'recuperacion',
    flavor: 'Limon',
    featured: true,
    active: true,
    image: '/products/bcaa-sabor-limon-400g.png',
    images: ['/products/bcaa-sabor-limon-400g.png'],
  },
  {
    name: 'Pre Workout Xtreme 350 g',
    slug: 'pre-workout-350g',
    description:
      'Pre entreno con 300 mg de cafeina, 6 g de citrulina y 3.2 g de beta alanina para sesiones intensas, foco y empuje sostenido.',
    price: 28990,
    comparePrice: 32990,
    stock: 14,
    category: 'pre-entrenos',
    brand: 'Iron Fuel',
    goal: 'energia',
    flavor: 'Frutos rojos',
    featured: true,
    active: true,
    image: '/products/pre-workout-350g.png',
    images: ['/products/pre-workout-350g.png'],
  },
  {
    name: 'Protein Bar 20 g Chocolate Brownie',
    slug: 'protein-bar-20g',
    description:
      'Barra proteica baja en azucares con 20 g de proteina, pensada para colaciones practicas, saciedad y aporte proteico entre comidas.',
    price: 4990,
    comparePrice: 5990,
    stock: 32,
    category: 'snacks-proteicos',
    brand: 'Iron Fuel',
    goal: 'nutricion',
    flavor: 'Chocolate Brownie',
    featured: true,
    active: true,
    image: '/products/protein-bar-20g.png',
    images: ['/products/protein-bar-20g.png'],
  },
  {
    name: 'Creatine Monohydrate Micronized 300 g',
    slug: 'creatina-monohidratada-300g',
    description:
      'Creatina micronizada sin sabor para fuerza, rendimiento y recuperacion en etapas de progreso deportivo.',
    price: 24990,
    comparePrice: 27990,
    stock: 18,
    category: 'creatina',
    brand: 'Iron Fuel',
    goal: 'fuerza',
    flavor: 'Sin sabor',
    featured: true,
    active: true,
    image: '/products/creatina-monohidratada-300g.png',
    images: ['/products/creatina-monohidratada-300g.png'],
  },
  {
    name: 'Whey Protein 900 g Chocolate',
    slug: 'whey-protein-900g',
    description:
      'Proteina whey isolate + concentrate con 24 g de proteina por servicio, 5.5 g de BCAA y 4 g de glutamina.',
    price: 37990,
    comparePrice: 41990,
    stock: 15,
    category: 'proteinas',
    brand: 'Iron Fuel',
    goal: 'masa-muscular',
    flavor: 'Chocolate',
    featured: true,
    active: true,
    image: '/products/whey-protein-900g.png',
    images: ['/products/whey-protein-900g.png'],
  },
]
